import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "XSP",
    name: "X-Stakepool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://xstakepool.com/image/xsp-icon64.png",
    sources: ["https://xstakepool.com/feed/"],
    twitterUsername: "btbfpark",
  },
 {
    id: "DOW",
    name: "DOW Pool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://raw.githubusercontent.com/Dow-shi/cardano-stake-pool/main/logo.png",
    sources: ["https://expo-dow.com/feed/"],
    twitterUsername: "Dow_shi1",
  },
  {
    id: "COFFEE",
    name: "COFFEE POOL",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://coffeepool.jp/poolicon.png",
    sources: ["https://coffeepool.jp/feed/"],
    twitterUsername: "hix_coffeepool",
  },
  {
    id: "MYB",
    name: "MIYABI KYOTO",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://miyabi-kyoto.org/wp-content/uploads/2021/07/miyabi_64.png",
    sources: ["https://miyabi-kyoto.org/feed/"],
    twitterUsername: "Miyabi_Kyoto_",
  },
   {
    id: "WYAM",
    name: "WYAM-StakePool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://wyam-stakepool.com/WYAM_icon64.png",
    sources: ["https://wyam-stakepool.com/feed/"],
    twitterUsername: "WYAM_StakePool",
  },
   {
    id: "SAKE",
    name: "Sake Pool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://user-images.githubusercontent.com/85638021/151510654-1d8565d7-4558-48d5-81dc-a5b65d48379c.png",
    sources: ["https://sakepool.com/feed.xml"],
    twitterUsername: "sakepool_ada",
  },
   {
    id: "SUGAR",
    name: "Sugar Stake Pool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://raw.githubusercontent.com/sitaki/metadata/main/images/icon_64x64.png",
    sources: ["https://note.com/cardano_sugar/m/m14e3ecc96dd2/rss"],
    twitterUsername: "sugar417K",
  },
   {
    id: "NIZI",
    name: "NIZI Stake Pool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://nizi-stake-pool.com/NIZIicon.png",
    sources: ["https://nizi-stake-pool.com/feed/"],
    twitterUsername: "sNiziStake",
  }, 
  {
    id: "JSP",
    name: "Japanese Stake Pool",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://pbs.twimg.com/profile_images/1387325125867892740/JUuqRrB3_400x400.jpg",
    sources: ["https://www.youtube.com/feeds/videos.xml?channel_id=UCBWyk1XiT0qRQwHYuasyv4Q"],
    twitterUsername: "cardano_spo",
  },
   {
    id: "NAP",
    name: "NEKOTA ADA POOL",
    role: "SPO",
    bio: "SPO",
    avatarSrc: "https://www.publickey.co.jp/files/nap_log_maru_tw64.png",
    sources: ["https://www.youtube.com/feeds/videos.xml?channel_id=UCz3QzD1qX5fm1KqQGGZhR0A"],
    twitterUsername: "necotaSensei",
  },
];
